### ISSUE TITLE
Does not allow to build anything

### ISSUE THREAD

**Issue by LaGallinaTuruleta** [alextd/RimWorld-ReplaceStuff#19]
Hello, 
At first, thanks for all your work developing.
I don't commonly share issues, any upturn is well accepted.
I just added some of your mods to my 1.1 save and It doesn't crash loading.
Instead trying to "build" (not talking about the first click when you select the building instead the second click where you place it on the map) It verboses this [error](https://textuploader.com/16pij)
Desactivating this mod give me no more error.
This is my actual [ModsConfig](https://textuploader.com/16pi4)
I would like to know if I could do something. 
Thanks in advance.

**Comment by alextd** [comment]
Ah geez, this is all over the Steam Workshop page, TL;DR nothing for me to do, HugsLibs/HarmonyLib update 2.0.0.7 broke things
