### ISSUE TITLE
Issues when loading the mod

### ISSUE THREAD

**Issue by ThomasLuxembourg** [alextd/RimWorld-ReplaceStuff#34]
Hi, I get those logs :

`Mod Replace Stuff is missing packageId in About.xml! (example: <packageId>AuthorName.ModName.Specific</packageId>) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)`

and :

`Could not find a type named Replace_Stuff.Designator_ReplaceStuff 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)`

Also the mod is yellow (apparently not updated) :

`Mod  is missing supported versions list in About.xml! (example: <supportedVersions><li>1.0</li></supportedVersions>) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)`

Is the issue specific to me or due to modifications in the code ?

**Comment by alextd** [comment]
Looks like you downloaded the source instead of a release.
