### ISSUE TITLE
Haulers mine stone

### ISSUE THREAD

**Issue by uzver91** [alextd/RimWorld-ReplaceStuff#36]
Hello.
I understand that my constructors can mine stone when replace it to wall, but why every hauler can do it too? Instead of "hauling materials to blueprint-go to next-repeat" behavior they try to mine one block of stone (with 0-1 skill) all day long, and than they can carry materials. 
Is there any chance to fix this up? I cant found solution myself.

**Comment by alextd** [comment]
![image](https://user-images.githubusercontent.com/101399/161101525-42854329-0da9-4e55-8036-8fe7b3954f33.png)

It's already a vanilla problem that haulers do jobs they're not good at, eg building over trees like here. That'd be some extra special thought to fix that.

**Comment by uzver91** [comment]
I notice one thing today. If pawn needs to haul exist building to a blueprint, that logic work much better. Mine first, move building second. I just need to get used to.
Your mod is awesome, btw, thanks!
